inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

plugins:
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/vagrant-k8s.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec:
  Language:
    Expectations:
      - expect
